num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
num3 = int(input("Enter the first number: "))
num4 = int(input("Enter the second number: "))
num5 = int(input("Enter the second number: "))
if (num1 > num2) 
